### PR TITLE
Bounded Optimizer

### PR DESCRIPTION
**Pull request by borcuttjahns**

### CODE REVIEW

**Comment by borcuttjahns** [comment]
@aarmey @andrewram4287 I tried out bounding the optimizer values and it seems to remedy a lot of the failed optimization problems and the issue of some clusters having no cells at the cost of a lot of speed. Doesn't have to be merged now but just food for thought.

**Comment by aarmey** [comment]
It looks like the log-likelihood gets quite a bit worse, though? You can just bound `nk` by setting the bounds for the other unknowns to `(-np.inf, np.inf)`.

I'm sure we'll eventually

**Comment by aarmey** [comment]
(Accidentally hit buttons while typing.)

**Comment by borcuttjahns** [comment]
Ok - I'll need to play with it some more but I think another benefit that the constraints had is that maybe 70% of the time the unbounded solver fails due to some covariance and factor values blowing up to things like 1e67 etc. - I'll try to locate some more relaxed bounds that still prevent this behavior without sacrificing LL and then merge this.

**Comment by borcuttjahns** [comment]
If what we talked about is true then this should be set to merge - also if it's alright with you at some point could I get moderator/admin privileges so I can merge smaller things myself?

**Comment by aarmey** [comment]
@borcuttjahns changed you to admin.

**Pull request merged**
