### PR TITLE
Moving data frames to xarray

### PR DESCRIPTION
**Pull request by andrewram4287**
Altering numpy arrays and dataframes to be an xarray or xarray dataset

### CODE REVIEW

**Comment by aarmey** [comment]
@andrewram4287 nice. If you have this setup, can you move the figure plotting code to take advantage of this? This should be able to replace a lot of the code that reintegrates the factors with labels into a data frame.

**Comment by andrewram4287** [comment]
> @andrewram4287 nice. If you have this setup, can you move the figure plotting code to take advantage of this? This should be able to replace a lot of the code that reintegrates the factors with labels into a data frame.

Sounds good!

**Comment by andrewram4287** [comment]
@aarmey let me know if you'd like me to make more changes

**Review by aarmey — APPROVED** [review]
This works! Merging.

**Pull request merged**
