### PR TITLE
Start Allowing Negs Alternate

### PR DESCRIPTION
**Pull request by borcuttjahns**
Didn't see the other allowing negatives approach but this seems to get a bit closer to what I think we were talking about. I'm a bit confused to the math here since most of the calculations revolve around using the covariance cholesky and I'm not sure there's a direct way of calculating how exponentiating affects that. Right now to make sure the covariances are positive I'm just exponentiating all the ingredients for that calculation. I've also removed the bounds and exponents for other calculations. Clustering looks _ok_ but not great for the now negative beach scene. Will look more later. @andrewram4287 I think this might be a good discussion/jumping off PR?

### CODE REVIEW

**Comment by aarmey** [comment]
@borcuttjahns @andrewram4287 thanks for playing with this. What I'm not able to reconcile from my suggested approach is this: On a linear scale, a negative number has a negative effect, zero has no effect, and a positive number has a positive effect. Exponentiation causes negative numbers to have little effect, zero have some effect, etc. This doesn't seem consistent with what we would want... if the condition factor matrix has a negative entry, it **should** cause negative movement in position, but I'm not sure what I should expect regarding the covariance. If we could settle on how the factor matrices should lead to changes in the GMM properties, then we can find a mathematical representation.

At least in the non-negative case, we can think of the factors as some sort of partial "assignment" of features to each output. (We can discuss what I mean sometime.) So, I don't know that our current non-negative approach is optimal, but it's not **certain** to be an outright bad idea.

So, I see three options at the moment:

1. We retain the current approach. I don't **know** that it's wrong, but does seem to be challenging to interpret.
2. The GMM properties are separately approximated, such that there are separate factor matrices for the position, mixing coefficient, and covariance. This bypasses the issue of non-negativity, since the position can have negativity but then the covariance factors be solved in a non-negative way. However, I'm not sure what it means to have multiple factor matrices representing seemingly common dimensions.
3. There may be some more theoretical work out there that more deeply investigates this problem. I haven't found anything, but exploring the literature more may be helpful.

Let me know what you think.

**Comment by borcuttjahns** [comment]
@andrewram4287 @aarmey I've been thinking about the issue and had the following thoughts about what you're saying: After reviewing your comments about why you're hesitant to have factors with varying scales of transformation depending on where they're used (mean or cov) I started to maybe lean towards option 2 which you had offered. My reasoning there and potentially a problem I have with the current approach is that although there are of course shared axes between the mean and covariance factorizations I've been startling to struggle with whether covariance and mean factor patterns should be encoded by the same factors.

For example: if you were to have a population that has low marker measurements but huge variance when treated with low drug concentrations and then at higher drug concentrations, marker expression increases and variance decreases, those two patterns would be hard to reconcile in a single concentration factors plot. Likely what you would see is two factors that had opposing relationships in that one might grow larger and one might get smaller at higher concentrations, but that only one of them would be weighted in marker space - however, this is also inherently difficult to talk about considering you would have to bring covariance factors into the discussion. I also think this might be why it takes at 4 or so factors to fit the beach situation, since the sun is moving but the variance is not - a covariance factor or two might be required to reconcile covariance with sun movement. Potentially fitting mean and covariance tensors separately allows for a more focused analysis of mean and covariance rather than having to inherently look at both of them while inspecting output. Of course fitting separately would also likely mean better fits with smaller rank as well at the cost of more total variables.

I suppose this quickly turns into a pros and cons game when thinking about how you want to be able to talk about the method but let me know your thoughts - if you think there's some promise to that approach I can go ahead and try to start a branch exploring if it works! Of course, you may still think some combo of the first approach of sharing axes and allowing or not allowing negatives is better - in that case let me know as well. Also would be happy to talk this over on Zoom.

**Comment by aarmey** [comment]
@borcuttjahns (& @andrewram4287) I've had many of the same thoughts—in short, I don't like that splitting into mean and covariance factors separates the interpretation of these, but I think this problem already occurs when they are combined. Your description of challenges interpreting the current factors is evidence of this.

If you can picture how the code would change to make separate factors, why don't you make an attempt at implementing this. One observation I initially thought of as a limitation is that there will be a separate rank of the mean and covariance. However, I think it may be a feature to enforce additional simplicity in the covariance patterns compared to those for the mean. Long-term (as in maybe not even within this paper) this change may also make it possible to iteratively solve for the factors like ALS, rather than using our optimization approach, since it simplifies the relationship between each factor matrix and the data. (Which could remove the starting point influence.)

You're right that this is all about pros and cons—in theory either approach can approximate the data. However, the core value of the method is getting this right such that it's possible to interpret these complicated datasets. You can see similar tradeoffs between e.g., PCA, U-MAP, tSNE, LDA, etc.

If you hit a snag in implementing this, let me know; I should be available all of tomorrow.

**Comment by andrewram4287** [comment]
@aarmey After my discussion with @borcuttjahns I do agree option 2 will make the most sense. Currently right now we always assume that based on factors, we can never tell if a marker/gene is increasing or decreasing. But like we discussed during my presentation and during subgroup, the interpretation will be more complex to get our point across if we separate the factors for the mean and covariance, and we will be need to look at many more variables. But like Brian said, expanding the factors might give us more insight to the data since they are explaining different aspects of the data.

**Pull request closed without merging**
