### PR TITLE
Plotting original data set and synthetic cells of tGMM fit

### PR DESCRIPTION
**Pull request by andrewram4287**
Plotting the original dataset for a specific ligand and time, and comparing that to synthetic data points based on the output of the minimization function.

### CODE REVIEW

**Comment by aarmey** [comment]
Interesting. A few thoughts:

1. It looks like the real data has a hard cutoff at 0. Is this the more recent hlog normalization?
2. Can you reduce the size of the points so it's easier to see the density?
3. Any thoughts about overall whether it's fitting well?

**Comment by andrewram4287** [comment]
> Interesting. A few thoughts:
> 
> 1. It looks like the real data has a hard cutoff at 0. Is this the more recent hlog normalization?
> 2. Can you reduce the size of the points so it's easier to see the density?
> 3. Any thoughts about overall whether it's fitting well?



> Interesting. A few thoughts:
> 
> 1. It looks like the real data has a hard cutoff at 0. Is this the more recent hlog normalization?
> 2. Can you reduce the size of the points so it's easier to see the density?
> 3. Any thoughts about overall whether it's fitting well?

1. No, this is with our initial normalization, where we just divide by the std per experiment. We also divide by the pSTAT5 std of all the experiments combined. 
2. On it!
3. It seems as if for smaller concentrations, it is not able to capture the variability, but for the higher concentrations the fit seems to do a decent job at capturing the spread of the markers

**Comment by aarmey** [comment]
Ok, try this with hlog too and see how it looks.

**Comment by andrewram4287** [comment]
@aarmey I'd like to merge this PR if doesn't need more changes.

**Comment by aarmey** [comment]
Looks reasonable to me. Merging!

**Pull request merged**
